/* eslint-disable prettier/prettier */
const ScreenNames = {
  Splash: 'Splash',
  Welcome: 'Welcome',
  SignIn: 'SignIn',
  SignUp: 'SignUp',
  ForgotPassword: 'ForgotPassword',
  ResetPassword: 'ResetPassword',
  VerifyOtp: 'VerifyOtp',
  NoInternet: 'NoInternet',
  BottomTab: 'BottomTab',
  Drawer: 'Drawer',
  Home: 'Home',
  SubscriptionPlans: 'SubscriptionPlans',
  Payment: 'Payment',
  Notification: 'Notification',
  SharedRoutine: 'SharedRoutine',
  SharedRoutineComments: 'SharedRoutineComments',
  AddNewRoutine: 'AddNewRoutine',
  EditTask: 'EditTask',
  Routine: 'Routine',
  Community: 'Community',
  MyCommunity: 'MyCommunity',
  Profile: 'Profile',
  RoutineDetailsWithTask: 'RoutineDetailsWithTask',
  Messages: 'Messages',
  FollowedCommunity: 'FollowedCommunity',
  EditProfile: 'EditProfile',
  ChangePassword: 'ChangePassword',
  Journals: 'Journals',
  AddNewJournals: 'AddNewJournals',
  JournalsInfo: 'JournalsInfo',
  Review: 'Review',
  RejectedCommunityRequest: 'RejectedCommunityRequest',
  AllComments: 'AllComments',
  FollowedCommunityDetails: 'FollowedCommunityDetails',
  FollowedCommunityPost: 'FollowedCommunityPost',
  Task: 'EditTask',
  CustomRoutineDateTime: 'CustomRoutineDateTime',
  AddNewPost: 'AddNewPost',
  Chat: 'Chat',
  Contact: 'Contact',
  ContactForQuery: 'ContactForQuery',
  TermAndCondition: 'TermAndCondition',
  Privacy: 'Privacy',
  Search: 'Search',
  MemberList: 'MemberList',
  Calendar: 'Calendar',
  DownloadJournal: 'DownloadJournal'
};

export default ScreenNames;
